# Generated by Django 2.2 on 2019-05-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('from_currency', models.CharField(max_length=255)),
                ('to_currency', models.CharField(max_length=255)),
                ('exchange_rate', models.FloatField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
