# Generated by Django 2.2 on 2019-05-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_text', models.TextField(max_length=250)),
                ('event_date', models.DateTimeField()),
            ],
        ),
    ]
