# Generated by Django 2.2 on 2019-04-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='owner',
            field=models.CharField(max_length=20),
        ),
    ]
